version: '3.8'

services:
  #  msauth:
  #    build:
  #      context: ./apps/msauth
  #      dockerfile: Dockerfile
  #    container_name: msauth
  #    ports:
  #      - "8001:8001"
  postgres1:
    image: postgres:16.3-alpine3.20
    container_name: clients
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
   image: postgres:16.3-alpine3.20
   container_name: products
   environment:
     POSTGRES_USER: user2
     POSTGRES_PASSWORD: password2
     POSTGRES_DB: products_db
   ports:
     - "5433:5432"
   volumes:
     - postgres2_data:/var/lib/postgresql/data

  postgres3:
   image: postgres:16.3-alpine3.20
   container_name: carts
   environment:
     POSTGRES_USER: user3
     POSTGRES_PASSWORD: password3
     POSTGRES_DB: carts_db
   ports:
     - "5434:5432"
   volumes:
     - postgres3_data:/var/lib/postgresql/data

  postgres4:
   image: postgres:16.3-alpine3.20
   container_name: payment
   environment:
     POSTGRES_USER: user4
     POSTGRES_PASSWORD: password4
     POSTGRES_DB: payment_db
   ports:
     - "5435:5432"
   volumes:
     - postgres4_data:/var/lib/postgresql/data


volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:
  postgres4_data:
