version: '3.8'

volumes:
  postgres1_data:

services:

  postgres-payment:
    container_name: postgres-payment
    image: postgres:16.3-alpine3.20

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3Mu9o82cGm0CoejxSEE0INVZhHmWibCS"
      PGDATA: "/data/postgres"
      PGPORT: 5435

    volumes:
       - postgres1_data:/var/lib/postgresql/data

    ports:
      - "5435:5435"
    restart: unless-stopped

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

