server:
  port: 8003

spring:
  application:
    name: mscart
  datasource:
    url: jdbc:postgresql://postgres-cart:5434/cart_db
    username: postgres
    password: 3Mu9o82cGm0CoejxSEE0INVZhHmWibCS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
