server:
  port: 8082

spring:
  application:
    name: mscart
  datasource:
    url: jdbc:postgresql://localhost:5434/cart_db
    username: user3
    password: password3


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
