server:
  port: 8003

spring:
  application:
    name: mscart
  datasource:
    url:      ${db.uri.auth}
    username: ${db.username.auth}
    password: ${db.password.auth}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
