version: '3.8'

volumes:
  #  auth-db:
  postgres1_data:

services:
  #  auth-ms:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: auth-ms
  #    ports:
  #      - "8001:8001"
  postgres1:
    image: postgres:16.3-alpine3.20
    container_name: clientes
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

#  mongodb:
#    image: mongo:5.0-rc-focal
#    container_name: auth-db
#    ports:
#      - '27018:27017'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: 12345
#      MONGO_INITDB_DATABASE: auth-db
#    volumes:
#      - auth-db:/data/db