version: '3.8'

volumes:
  postgres1_data:

services:

  postgres-auth:
    container_name: postgres-auth
    image: postgres:16.3-alpine3.20

    environment:
      POSTGRES_DB: clients_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3Mu9o82cGm0CoejxSEE0INVZhHmWibCS"
      PGDATA: "/data/postgres"

    volumes:
       - postgres1_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    restart: unless-stopped

    networks:
      - app-network

  auth-ms:
    image: 'auth-ms:0.0.1'
    build:
      context: .
    container_name: auth_ms

    ports:
      - "8001:8001"

    networks:
      - app-network

    environment:
      WAIT_HOSTS: postgres-auth:5432
      DB_URI_AUTH: jdbc:postgresql://postgres-auth:5432/clients_db
      DB_USERNAME_AUTH: postgres
      DB_PASSWORD_AUTH: 3Mu9o82cGm0CoejxSEE0INVZhHmWibCS

    command: sh -c "/wait && java -jar /app/auth_ms.jar"

networks:
  app-network:
    driver: bridge

